### PR TITLE
Implement frontend discovery through Myth/GetFrontend

### PR DESCRIPTION
**Pull request by rajlaud**
An initial attempt to implement frontend discovery through Myth/GetFrontend, fixing issue #43. Based on `issue37` branch because it needs a separate frontend and backend object. I also merged in PR #46.

I've made some changes to the separation of frontend and backend; in particular, I didn't understand why there were two different backend/API objects.

This needs more testing (and likely discussion) before being merged.

### CODE REVIEW

**Comment by calmor15014** [comment]
@rajlaud - thanks for jumping in and keeping this moving!  Just in a quick review of the commits, looks like where we wanted to go.

I am swamped at work this week but plan to review this over the weekend.  I'm also doing some upgrades on my end this weekend to my production Home Assistant installation so it's perfect timing.

Just FYI, the reason there were two different backend/API objects in `__init__.py` was because the thought/hope was that the API connector could be encapsulated in one object and only need one initiation of it, and the backend could be its own object.  This was going to be almost necessary to keep the code organized if we had to put the `requests` calls into the integration itself, but that goes against Home Assistant development practices.  So, though the API is still not yet PyPI installable, I was part way through determining if it still made sense to have one instance of the API access that the frontend and backend objects could refer to, or if they should just call the API independently... but was leaning toward the latter anyway, which is the direction you went too.

issue43 branch is a dev branch anyway (still kind of learning GitHub) and there's no guarantee it's in a functional state, so if you want it merged in, mark it ready for review and once I get into the review I can merge to issue43 at least so others could easily give it a test.  Then we can see what we need to do to get it into master.

**Comment by rajlaud** [comment]
Thanks @calmor15014

**Comment by calmor15014** [comment]
I pulled the changes onto a fresh test instance of HA, but it didn't find any frontend devices.  If I manually configure a frontend, it works normally.

The debug logs indicate "Started frontend discovery" and the "Got frontends" information arrives on the 60-second interval, complete with all of the information for each frontend, but it's not triggering HA to add any entities, nor alert that new entities are avaiable.  Shut one off and it dropped off the list.  So, that much is working.

Running whatever the latest Home Assistant version is as of today. (0.112.4?)

I'll add a few more debug statements in the discovery code and see what else it needs.

**Comment by calmor15014** [comment]
It's getting to the point that it determines that it needs to call load_platform, calls it, and returns from the call, but setup_platform in media_player.py is never called, whether a frontend is manually configured or not.  I put a logging entry as the first thing it does when it enters setup_platform, but it never fires.  

It finds the manually configured one in the list and does not try to add that one.  Just the new frontends are attempted to be added, but the call never seems to succeed.

The only thing I can think of is that in the core code for load_platform, which creates a an async job, it appears to look for the component type first and fails (silently unless listening I suppose) unless it's not in the list of components for some reason?  From async_load_platform:

`   if component not in hass.config.components:`
`        setup_success = await setup.async_setup_component(hass, component, hass_config)`

`   # No need to fire event if we could not set up component`
`    if not setup_success:`
`        return`

I confirmed it was getting the domain and component type (media_player) correct in the call... I'm not familiar with how discovery works though so I'm not sure where to look next.

**Comment by calmor15014** [comment]
After further probing, load_platform was failing because MP_DOMAIN and DOMAIN are swapped.  Putting MP_DOMAIN first and DOMAIN second allows it to reach media_player.py and setup_platform, but it fails as it tries to put the discovery platform into the config object... so that will need sorted out.

**Comment by rajlaud** [comment]
Thanks for testing this. I'll take a look and push some updates today.

**Comment by rajlaud** [comment]
Fixed it. I can't reuse `PLATFORM_SCHEMA` this way. Instead I created a shared schema used by both `PLATFORM_SCHEMA` and `DISCOVERY_SCHEMA`.

I also added an optional parameter `mythtv_id`, which should be the unique frontend id.

**Comment by calmor15014** [comment]
Tested and confirmed that Home Assistant did in fact pick up other frontends and added them as entities.  Those media_player entities could then be controlled.

One quick question, what are some of the uses for the mythtv_id?  Right now it looks just mapped to the frontend name, so is there something more we can do with it?

I'm going to merge this PR, but there is still a bit more testing that may need to be done.

- Discovered frontends have a power button, but realistically there is no way to turn on or off without manual configuration as there's no MAC address for WoL and no SYSEVENT config
- I have an Android TV which runs Kodi; it reports as an online frontend when the TV is off, and is throwing a bunch of WARNING level logs due to failing the GetStatus call.

Thanks for getting this to work.  Will go a long way toward some of the other things I'm working on regarding setup of binary sensors and such.

**Comment by rajlaud** [comment]
Thanks calmor. Agree there is more to be done here. In particular, I'm not sure how to gracefully discover frontend features. I think the long term solution is to move to a configuration flow setup. The backend can discover frontends, and then you specify their configuration from the Home Assistant `integrations` panel. In the meantime, you can always configure everything in the yaml file, and just take advantage of the fact that frontends can come and go now. A frontend set up through the yaml file will keep its configuration even if it disconnects and later reconnects.

The `Name` field from GetFrontends is a unique identifier (like a hostname). The `name` currently in the yaml config is more like a friendly name/display name. The reason for the `mythtv_id` field is that it allows you to specify the unique identifier before the GetFrontends API call discovers it. It might be less confusing if we call `mythtv_id` `name` and change the current `name` to `friendly_name`.

The reason I added it is because without it, the discovery process could discover a frontend that you were trying to setup through yaml, leading to duplicate entries for the same frontend. This only happens if the frontend was disconnected when home assistant started, such that GetFrontends couldn't grab the identifier.

**Comment by calmor15014** [comment]
@rajlaud - No, thank you for contributing!  I had some `binary_sensor` code written to detect recorders and status.  It wasn't yet committed when you sent in the PR, but your work will make it much cleaner to set up with discovery instead of adding to the yaml.

Thanks for the explanation about the `mythtv_id` vs `name` - we will have to figure that out going forward for sure.

One other issue I see is that after shutting off a "discovered" frontend, it does not show the status as unavailable, and it's also throwing up the same errors as the Kodi frontend.  Just things to work through, but we'll get there.  Discovery itself is working though, so the rest is a separate issue perhaps.

As for getting the frontend capabilities, we are already getting volume control function in `media_player` so there is some capability to query the frontend directly with the frontend service.

System WoL and shutdown events are not part of the frontend player itself, though, so there's really no easy way to identify their presence without getting crazy.  It may be easier to just remove power on/off control from discovery-added frontends altogether and leave it in the yaml, as those take some more advanced config on the MythTV and networking side anyway.

**Pull request merged**
