### PR TITLE
Remove Services API GitHub requirement, remove error check for host 

### LINKED ISSUE #14: Keep up with changes to mythtv_services_api
The services API is being updated as we develop this. How should we keep up?
1. We can update the platform to use the latest GitHub commit and version number (as of now, this has moved on from the version referred to by our code). I noticed this seems to install it each time you run `hass`.
2.Just expect it to be available and install using pip in the virtual environment. This is not automatic, but shouldn't re-download/install each time.
When we submit/release the platform, we can pin it to a certain API version, which might be on PyPI by then.

### PR DESCRIPTION
**Pull request by lindsaymarkward**
No need to check for missing host since HA already handles this; remove source selection support since one frontend won't have multiple "sources", will it?
Closes #14

### CODE REVIEW

**Comment by calmor15014** [comment]
By the way I had envisioned using "Source" to drive MythTV's JumpPoints (i.e. Home Menu, Live TV, Recordings, Music, Pictures, etc...) but I don't think SendAction does that well, and not sure how to update HA based on actual status.

**Comment by lindsaymarkward** [comment]
A single _ at the start of a Python function/method indicates "weak internal use". It will only be used by the class itself, not outside the class. In Java it would be `private`. Yes, other non-public (not for external use) functions should start with _ too. I didn't really go through them :)

Sorry I forgot to update the README. At this stage, I'm still expecting we're writing it only for each other!

That idea for source select could be cool. Go for it if you can make it work.
Did merging this PR automatically close #14 or did you have to do so manually?

**Comment by calmor15014** [comment]
It closed once I accepted and merged it to master. How did you set it to close the issue?

**Comment by lindsaymarkward** [comment]
I wrote `closes #14` in the PR, hoping that would work. I've seen it before, but not used it before. Nice.

**Pull request merged**
