### PR TITLE
Update for MythTVServicesAPI version 0.1.7

### PR DESCRIPTION
**Pull request by heytensai**
MythTVServicesAPI has changed to an object model. I have updated this code to match.

### CODE REVIEW

**Comment by calmor15014** [comment]
Now that the holidays are over, I think I finally got my server running to the point where I can spin up a test HA container and give this a test this week, but it looks like good work!  @lindsaymarkward has been interested in getting this into an official HA update, though I don't know if that can happen until MythTVServicesAPI can be installed automatically via pip or a static copy is included in this component.

**Comment by dshanske** [comment]
I'd really like this in. If you need any help testing...

**Comment by calmor15014** [comment]
Thanks @dshanske. I have a stable 0.28+fixes MythTV system and the latest HA version, both in LXC containers.  I intend to clone the HA container and run a test against my production MythTV system.  If you have MythTV 29 or 30-Pre please feel free to test and let me know the results as well.  I should be testing tomorrow (have other responsibilities today which prevent that).

**Comment by heytensai** [comment]
I tested this against MythTV 0.27 and found no issues. Play/pause even worked for me. That's unfortunately the only version of myth that I have access to. If there's anything else I can help with please advise.

**Comment by heytensai** [comment]
Actually I did find one issue, which was that the Services API checks the version string and doesn't like 0.27. I had to comment that bit out to get it to work. I submitted a pull request for them to add an optional parameter to ignore the version number. Given how old 0.27 is, I don't know that they'll bother.

**Comment by calmor15014** [comment]
Thanks @heytensai. 0.27 is old but not that old and the first version to support the API. I'm sure many still use it. 

I was unsuccessful in cloning my HA container today (unrelated issues with Proxmox) so I will test tomorrow. I may also talk with Bill on the Services API to see what the issue is for the version check. I know the older version-checked fine (he had 0.27, 0.28, and 29 listed independently) so he may update whatever broke between then and now.

**Comment by calmor15014** [comment]
@heytensai - I looked at the MythTVServicesAPI code and also your adds here.  I don't think there's any danger in leaving the novalidate option in, even though what will actually be installed when his 0.1.7 utilities are installed will ignore it.  I looked through and it appears that he pulled out the 0.27 version for automated testing purposes; it works for our case.

This version is confirmed to work normally on 0.28+fixes.  I don't have a v29 or v30-pre box to test on yet, but I can't see why these relatively simple functions would fail, since the MythTV API hasn't actually changed significantly at least as far as v29.

**Comment by heytensai** [comment]
Bill added in support for 0.27 and I confirmed it works for me, so I'm going to abandon the novalidate option for now. This is probably the cleaner fix anyway.

**Comment by heytensai** [comment]
Oh, I just noticed that you merged the novalidate change too. Well, it's up to you if you want to leave it in. Doesn't hurt anything I suppose.

**Comment by calmor15014** [comment]
I can remove it on the next change. If he updated to add in 0.27 support,
I'm sure there's a wheel version change that I'll need to update.

**Pull request merged**
